import { report } from "./harness";
import { runMathTests } from "./math.test";
import { runGeoTests } from "./geo.test";
import { runFlightTests } from "./flight.test";
import { runFlightModeTests } from "./flightModes.test";
import { runTerrainTests } from "./terrain.test";
import { runSimulationTests } from "./simulation.test";
import { runCollisionDamageTests, runDamageTests } from "./damage.test";
import { runLandingTests } from "./landing.test";
import { runLaunchTests } from "./launch.test";
import { runHudTests } from "./hud.test";
import { runFieldOsdTests, runOsdLayoutTests } from "./osdLayout.test";
import { runEnvironmentTests } from "./environment.test";
import { runWeatherTests } from "./weather.test";
import { runVideoLinkTests } from "./videoLink.test";
import { runAiTests } from "./ai.test";
import { runMissionTests } from "./mission.test";
import { runRaceTests } from "./race.test";
import { runFestivalTests } from "./festival.test";
import { runStreamerTests } from "./streamer.test";
import { runStrikeTests } from "./strike.test";
import { runOppositionTests } from "./opposition.test";
import { runControllerTests } from "./controller.test";
import { runKeyBindingTests } from "./keyBindings.test";
import { runAudioTests } from "./audio.test";
import { runMusicTests } from "./music.test";
import { runRenderTests } from "./render.test";
import { runPreloadTests } from "./preload.test";
import { runGpuTests } from "./gpu.test";
import { runExplosionTests } from "./explosion.test";
import { runPlayerTests } from "./player.test";
import { runIonTokenTests } from "./ionToken.test";
import { runUavTests } from "./uav.test";
import { runBuildTests } from "./builds.test";
import { runLiveryTests } from "./livery.test";
import { runPowerplantTests } from "./powerplant.test";
import { runMultirotorTests } from "./multirotor.test";
import { runGliderTests } from "./glider.test";
import { runRocketTests } from "./rocket.test";
import { runSkyeyeTests } from "./skyeye.test";

async function main(): Promise<void> {
  runMathTests();
  runGeoTests();
  runFlightTests();
  await runFlightModeTests();
  await runTerrainTests();
  await runSimulationTests();
  runDamageTests();
  await runCollisionDamageTests();
  await runLandingTests();
  await runLaunchTests();
  await runHudTests();
  runOsdLayoutTests();
  runFieldOsdTests();
  await runEnvironmentTests();
  runWeatherTests();
  await runVideoLinkTests();
  await runAiTests();
  await runMissionTests();
  await runRaceTests();
  await runFestivalTests();
  await runStreamerTests();
  await runStrikeTests();
  await runOppositionTests();
  runControllerTests();
  runKeyBindingTests();
  runAudioTests();
  runMusicTests();
  runRenderTests();
  runPreloadTests();
  runGpuTests();
  runExplosionTests();
  runPlayerTests();
  runIonTokenTests();
  runUavTests();
  runBuildTests();
  runLiveryTests();
  runPowerplantTests();
  await runMultirotorTests();
  runGliderTests();
  runRocketTests();
  runSkyeyeTests();
  report();
}

void main();
